---
- name: Update APT package index
  apt:
    update_cache: yes

- name: Install required packages for NodeSource
  apt:
    name: 
      - curl
      - software-properties-common
    state: present

- name: Download NodeSource setup script
  get_url:
    url: https://deb.nodesource.com/setup_21.x
    dest: /tmp/nodesource_setup.sh
    mode: '0755'

- name: Run NodeSource setup script
  command: bash /tmp/nodesource_setup.sh


- name: Install Node.js
  apt:
    name: nodejs
    state: present

