
    - name: Ensure curl is installed
      apt:
        name: curl
        state: present

    - name: Download NodeSource setup script
      get_url:
        url: https://deb.nodesource.com/setup_22.x
        dest: /tmp/nodesource_setup.sh
        mode: '0755'

    - name: Run NodeSource setup script
      command: bash /tmp/nodesource_setup.sh

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Verify Node.js installation
      command: node -v
      register: node_version

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create Nginx configuration file
      copy:
        dest: /etc/nginx/sites-available/astro.conf
        content: |
          server {
              listen 80;
              server_name k3vinsite.com www.k3vinsite.com;

              root /var/www/astro;
              index index.html;

              location / {
                  try_files $uri $uri/ /index.html;
              }
          }
      notify: reload nginx

    - name: Enable the site
      command: nginx -s reload
      notify: reload nginx

    - name: Remove the default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Display Node.js version
      debug:
        msg: "Node.js version installed: {{ node_version.stdout }}"